//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCompanion.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StudyCompanion.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ComputingSystems {
            get {
                return ResourceManager.GetString("ComputingSystems", resourceCulture);
            }
        }
        
        internal static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        internal static string OperatingSystems {
            get {
                return ResourceManager.GetString("OperatingSystems", resourceCulture);
            }
        }
        
        internal static string Bitencodings {
            get {
                return ResourceManager.GetString("Bitencodings", resourceCulture);
            }
        }
        
        internal static string PageReplacement {
            get {
                return ResourceManager.GetString("PageReplacement", resourceCulture);
            }
        }
        
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        internal static string NewValues {
            get {
                return ResourceManager.GetString("NewValues", resourceCulture);
            }
        }
        
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        internal static string ShowSolution {
            get {
                return ResourceManager.GetString("ShowSolution", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Profs {
            get {
                return ResourceManager.GetString("Profs", resourceCulture);
            }
        }
        
        internal static string Mensa {
            get {
                return ResourceManager.GetString("Mensa", resourceCulture);
            }
        }
        
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        internal static string PricesLabel {
            get {
                return ResourceManager.GetString("PricesLabel", resourceCulture);
            }
        }
        
        internal static string Allergens {
            get {
                return ResourceManager.GetString("Allergens", resourceCulture);
            }
        }
        
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        internal static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        internal static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        internal static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        internal static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        internal static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        internal static string A10 {
            get {
                return ResourceManager.GetString("A10", resourceCulture);
            }
        }
        
        internal static string A11 {
            get {
                return ResourceManager.GetString("A11", resourceCulture);
            }
        }
        
        internal static string A12 {
            get {
                return ResourceManager.GetString("A12", resourceCulture);
            }
        }
        
        internal static string A13 {
            get {
                return ResourceManager.GetString("A13", resourceCulture);
            }
        }
        
        internal static string A14 {
            get {
                return ResourceManager.GetString("A14", resourceCulture);
            }
        }
        
        internal static string Additives {
            get {
                return ResourceManager.GetString("Additives", resourceCulture);
            }
        }
        
        internal static string Z1 {
            get {
                return ResourceManager.GetString("Z1", resourceCulture);
            }
        }
        
        internal static string Z2 {
            get {
                return ResourceManager.GetString("Z2", resourceCulture);
            }
        }
        
        internal static string Z3 {
            get {
                return ResourceManager.GetString("Z3", resourceCulture);
            }
        }
        
        internal static string Z4 {
            get {
                return ResourceManager.GetString("Z4", resourceCulture);
            }
        }
        
        internal static string Z5 {
            get {
                return ResourceManager.GetString("Z5", resourceCulture);
            }
        }
        
        internal static string Z6 {
            get {
                return ResourceManager.GetString("Z6", resourceCulture);
            }
        }
        
        internal static string Z7 {
            get {
                return ResourceManager.GetString("Z7", resourceCulture);
            }
        }
        
        internal static string Z8 {
            get {
                return ResourceManager.GetString("Z8", resourceCulture);
            }
        }
        
        internal static string Z9 {
            get {
                return ResourceManager.GetString("Z9", resourceCulture);
            }
        }
        
        internal static string Z10 {
            get {
                return ResourceManager.GetString("Z10", resourceCulture);
            }
        }
        
        internal static string Z11 {
            get {
                return ResourceManager.GetString("Z11", resourceCulture);
            }
        }
        
        internal static string Z12 {
            get {
                return ResourceManager.GetString("Z12", resourceCulture);
            }
        }
        
        internal static string Z13 {
            get {
                return ResourceManager.GetString("Z13", resourceCulture);
            }
        }
        
        internal static string Z14 {
            get {
                return ResourceManager.GetString("Z14", resourceCulture);
            }
        }
        
        internal static string Z15 {
            get {
                return ResourceManager.GetString("Z15", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        internal static string MensaInfo {
            get {
                return ResourceManager.GetString("MensaInfo", resourceCulture);
            }
        }
        
        internal static string IOSPermissions {
            get {
                return ResourceManager.GetString("IOSPermissions", resourceCulture);
            }
        }
        
        internal static string PermissionRationale {
            get {
                return ResourceManager.GetString("PermissionRationale", resourceCulture);
            }
        }
        
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        internal static string Maindishes {
            get {
                return ResourceManager.GetString("Maindishes", resourceCulture);
            }
        }
        
        internal static string Soups {
            get {
                return ResourceManager.GetString("Soups", resourceCulture);
            }
        }
        
        internal static string Sidedishes {
            get {
                return ResourceManager.GetString("Sidedishes", resourceCulture);
            }
        }
        
        internal static string Desserts {
            get {
                return ResourceManager.GetString("Desserts", resourceCulture);
            }
        }
        
        internal static string NoMeals {
            get {
                return ResourceManager.GetString("NoMeals", resourceCulture);
            }
        }
        
        internal static string NoCalendars {
            get {
                return ResourceManager.GetString("NoCalendars", resourceCulture);
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        internal static string Buddy {
            get {
                return ResourceManager.GetString("Buddy", resourceCulture);
            }
        }
        
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        internal static string MST {
            get {
                return ResourceManager.GetString("MST", resourceCulture);
            }
        }
        
        internal static string ShortestPaths {
            get {
                return ResourceManager.GetString("ShortestPaths", resourceCulture);
            }
        }
        
        internal static string Netmasks {
            get {
                return ResourceManager.GetString("Netmasks", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        internal static string RealtimeScheduling {
            get {
                return ResourceManager.GetString("RealtimeScheduling", resourceCulture);
            }
        }
        
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        internal static string CalendarExportQuery {
            get {
                return ResourceManager.GetString("CalendarExportQuery", resourceCulture);
            }
        }
        
        internal static string ExerciseBasicLayout {
            get {
                return ResourceManager.GetString("ExerciseBasicLayout", resourceCulture);
            }
        }
        
        internal static string StatusQuery {
            get {
                return ResourceManager.GetString("StatusQuery", resourceCulture);
            }
        }
        
        internal static string QueryInfo {
            get {
                return ResourceManager.GetString("QueryInfo", resourceCulture);
            }
        }
        
        internal static string InfoText_Buddy_Request {
            get {
                return ResourceManager.GetString("InfoText_Buddy_Request", resourceCulture);
            }
        }
        
        internal static string InfoText_Buddy_Final {
            get {
                return ResourceManager.GetString("InfoText_Buddy_Final", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_Element_Added {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_Element_Added_Empty {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added_Empty", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_Element_Added_NotInUse {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added_NotInUse", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_Element_Exists {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Exists", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_Fifo_Element_Added_Distance {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Fifo_Element_Added_Distance", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_LRU_Element_Added_Distance {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_LRU_Element_Added_Distance", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_Optimal_Element_Added_NotInUse {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Optimal_Element_Added_NotInUse", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_SecondChanceClock_Element_Added_NotPointer {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_SecondChanceClock_Element_Added_NotPointer", resourceCulture);
            }
        }
        
        internal static string InfoText_PageReplacement_SecondChanceClock_Element_Added_Pointer {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_SecondChanceClock_Element_Added_Pointer", resourceCulture);
            }
        }
        
        internal static string InfoText_RealTimeScheduling_EDF {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_EDF", resourceCulture);
            }
        }
        
        internal static string InfoText_RealTimeScheduling_EDF_Info {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_EDF_Info", resourceCulture);
            }
        }
        
        internal static string InfoText_RealTimeScheduling_RMS_High {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_High", resourceCulture);
            }
        }
        
        internal static string InfoText_RealTimeScheduling_RMS_Info {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Info", resourceCulture);
            }
        }
        
        internal static string InfoText_RealTimeScheduling_RMS_Low {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Low", resourceCulture);
            }
        }
        
        internal static string InfoText_RealTimeScheduling_RMS_Medium {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Medium", resourceCulture);
            }
        }
        
        internal static string TableLabel_CRC_Calculation {
            get {
                return ResourceManager.GetString("TableLabel_CRC_Calculation", resourceCulture);
            }
        }
        
        internal static string TableLabel_CRC_Check {
            get {
                return ResourceManager.GetString("TableLabel_CRC_Check", resourceCulture);
            }
        }
        
        internal static string TableLabel_PageReplacement_Distance {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Distance", resourceCulture);
            }
        }
        
        internal static string TableLabel_PageReplacement_Pointer {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Pointer", resourceCulture);
            }
        }
        
        internal static string TableLabel_PageReplacement_Reference {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Reference", resourceCulture);
            }
        }
        
        internal static string TableLabel_PageReplacement_Slot {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Slot", resourceCulture);
            }
        }
        
        internal static string MSTV_Info_1 {
            get {
                return ResourceManager.GetString("MSTV_Info_1", resourceCulture);
            }
        }
        
        internal static string MSTV_Info_2 {
            get {
                return ResourceManager.GetString("MSTV_Info_2", resourceCulture);
            }
        }
        
        internal static string MSTV_Info_3 {
            get {
                return ResourceManager.GetString("MSTV_Info_3", resourceCulture);
            }
        }
        
        internal static string MSTV_Info_4 {
            get {
                return ResourceManager.GetString("MSTV_Info_4", resourceCulture);
            }
        }
        
        internal static string ShortestPath_Info_1 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_1", resourceCulture);
            }
        }
        
        internal static string ShortestPath_Info_2 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_2", resourceCulture);
            }
        }
        
        internal static string ShortestPath_Info_3 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_3", resourceCulture);
            }
        }
        
        internal static string InfoText_BitEncoding {
            get {
                return ResourceManager.GetString("InfoText_BitEncoding", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_FirstComeFirstServed_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_FirstComeFirstServed_Info", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_Priority_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Priority_Info", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_ShortestJobFirst_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_ShortestJobFirst_Info", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_Calculation {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Calculation", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_Duration {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Duration", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_Priority {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Priority", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_Result {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Result", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_RoundRobin_AfterTimeUnit {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_AfterTimeUnit", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_RoundRobin_AfterTimeUnits {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_AfterTimeUnits", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_RoundRobin_Begin {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_Begin", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_RoundRobin_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_Info", resourceCulture);
            }
        }
        
        internal static string InfoText_Scheduling_RoundRobin_WaitingTime {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_WaitingTime", resourceCulture);
            }
        }
        
        internal static string InfoText_CRC_check {
            get {
                return ResourceManager.GetString("InfoText_CRC_check", resourceCulture);
            }
        }
        
        internal static string InfoText_CRC_check_Finish {
            get {
                return ResourceManager.GetString("InfoText_CRC_check_Finish", resourceCulture);
            }
        }
        
        internal static string InfoText_CRC_check_Start {
            get {
                return ResourceManager.GetString("InfoText_CRC_check_Start", resourceCulture);
            }
        }
        
        internal static string InfoText_CRC_evenStep {
            get {
                return ResourceManager.GetString("InfoText_CRC_evenStep", resourceCulture);
            }
        }
        
        internal static string InfoText_CRC_Start {
            get {
                return ResourceManager.GetString("InfoText_CRC_Start", resourceCulture);
            }
        }
        
        internal static string InfoText_CRC_unevenStep {
            get {
                return ResourceManager.GetString("InfoText_CRC_unevenStep", resourceCulture);
            }
        }
        
        internal static string title_statistics {
            get {
                return ResourceManager.GetString("title.statistics", resourceCulture);
            }
        }
        
        internal static string label_sum {
            get {
                return ResourceManager.GetString("label.sum", resourceCulture);
            }
        }
        
        internal static string label_correct {
            get {
                return ResourceManager.GetString("label.correct", resourceCulture);
            }
        }
        
        internal static string label_wrong {
            get {
                return ResourceManager.GetString("label.wrong", resourceCulture);
            }
        }
        
        internal static string label_skipped {
            get {
                return ResourceManager.GetString("label.skipped", resourceCulture);
            }
        }
        
        internal static string BinaryToDecimal {
            get {
                return ResourceManager.GetString("BinaryToDecimal", resourceCulture);
            }
        }
        
        internal static string DecimalToBinary {
            get {
                return ResourceManager.GetString("DecimalToBinary", resourceCulture);
            }
        }
        
        internal static string BinaryAddition {
            get {
                return ResourceManager.GetString("BinaryAddition", resourceCulture);
            }
        }
        
        internal static string TwosComplement {
            get {
                return ResourceManager.GetString("TwosComplement", resourceCulture);
            }
        }
        
        internal static string NormalForm {
            get {
                return ResourceManager.GetString("NormalForm", resourceCulture);
            }
        }
        
        internal static string NormalFormText {
            get {
                return ResourceManager.GetString("NormalFormText", resourceCulture);
            }
        }
        
        internal static string KVMap {
            get {
                return ResourceManager.GetString("KVMap", resourceCulture);
            }
        }
        
        internal static string QMC {
            get {
                return ResourceManager.GetString("QMC", resourceCulture);
            }
        }
        
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
    }
}
