//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISDCompanion.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ISDCompanion.Resx.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        internal static string OperatingSystems {
            get {
                return ResourceManager.GetString("OperatingSystems", resourceCulture);
            }
        }
        
        internal static string Bitencodings {
            get {
                return ResourceManager.GetString("Bitencodings", resourceCulture);
            }
        }
        
        internal static string PageReplacement {
            get {
                return ResourceManager.GetString("PageReplacement", resourceCulture);
            }
        }
        
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        internal static string NewValues {
            get {
                return ResourceManager.GetString("NewValues", resourceCulture);
            }
        }
        
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        internal static string ShowSolution {
            get {
                return ResourceManager.GetString("ShowSolution", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Profs {
            get {
                return ResourceManager.GetString("Profs", resourceCulture);
            }
        }
        
        internal static string Mensa {
            get {
                return ResourceManager.GetString("Mensa", resourceCulture);
            }
        }
        
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        internal static string PricesLabel {
            get {
                return ResourceManager.GetString("PricesLabel", resourceCulture);
            }
        }
        
        internal static string Allergens {
            get {
                return ResourceManager.GetString("Allergens", resourceCulture);
            }
        }
        
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        internal static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        internal static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        internal static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        internal static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        internal static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        internal static string A10 {
            get {
                return ResourceManager.GetString("A10", resourceCulture);
            }
        }
        
        internal static string A11 {
            get {
                return ResourceManager.GetString("A11", resourceCulture);
            }
        }
        
        internal static string A12 {
            get {
                return ResourceManager.GetString("A12", resourceCulture);
            }
        }
        
        internal static string A13 {
            get {
                return ResourceManager.GetString("A13", resourceCulture);
            }
        }
        
        internal static string A14 {
            get {
                return ResourceManager.GetString("A14", resourceCulture);
            }
        }
        
        internal static string Additives {
            get {
                return ResourceManager.GetString("Additives", resourceCulture);
            }
        }
        
        internal static string Z1 {
            get {
                return ResourceManager.GetString("Z1", resourceCulture);
            }
        }
        
        internal static string Z2 {
            get {
                return ResourceManager.GetString("Z2", resourceCulture);
            }
        }
        
        internal static string Z3 {
            get {
                return ResourceManager.GetString("Z3", resourceCulture);
            }
        }
        
        internal static string Z4 {
            get {
                return ResourceManager.GetString("Z4", resourceCulture);
            }
        }
        
        internal static string Z5 {
            get {
                return ResourceManager.GetString("Z5", resourceCulture);
            }
        }
        
        internal static string Z6 {
            get {
                return ResourceManager.GetString("Z6", resourceCulture);
            }
        }
        
        internal static string Z7 {
            get {
                return ResourceManager.GetString("Z7", resourceCulture);
            }
        }
        
        internal static string Z8 {
            get {
                return ResourceManager.GetString("Z8", resourceCulture);
            }
        }
        
        internal static string Z9 {
            get {
                return ResourceManager.GetString("Z9", resourceCulture);
            }
        }
        
        internal static string Z10 {
            get {
                return ResourceManager.GetString("Z10", resourceCulture);
            }
        }
        
        internal static string Z11 {
            get {
                return ResourceManager.GetString("Z11", resourceCulture);
            }
        }
        
        internal static string Z12 {
            get {
                return ResourceManager.GetString("Z12", resourceCulture);
            }
        }
        
        internal static string Z13 {
            get {
                return ResourceManager.GetString("Z13", resourceCulture);
            }
        }
        
        internal static string Z14 {
            get {
                return ResourceManager.GetString("Z14", resourceCulture);
            }
        }
        
        internal static string Z15 {
            get {
                return ResourceManager.GetString("Z15", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string MensaInfo {
            get {
                return ResourceManager.GetString("MensaInfo", resourceCulture);
            }
        }
        
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        internal static string Maindishes {
            get {
                return ResourceManager.GetString("Maindishes", resourceCulture);
            }
        }
        
        internal static string Soups {
            get {
                return ResourceManager.GetString("Soups", resourceCulture);
            }
        }
        
        internal static string Sidedishes {
            get {
                return ResourceManager.GetString("Sidedishes", resourceCulture);
            }
        }
        
        internal static string Desserts {
            get {
                return ResourceManager.GetString("Desserts", resourceCulture);
            }
        }
        
        internal static string NoMeals {
            get {
                return ResourceManager.GetString("NoMeals", resourceCulture);
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        internal static string Buddy {
            get {
                return ResourceManager.GetString("Buddy", resourceCulture);
            }
        }
        
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
    }
}
