//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISDCompanion.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISDCompanion.Resx.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glutenhaltig.
        /// </summary>
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senf und Senferzeugnisse.
        /// </summary>
        internal static string A10 {
            get {
                return ResourceManager.GetString("A10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesamsamen und Sesamsamenerzeugnisse.
        /// </summary>
        internal static string A11 {
            get {
                return ResourceManager.GetString("A11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwefeldioxid und Sulfite.
        /// </summary>
        internal static string A12 {
            get {
                return ResourceManager.GetString("A12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lupinen und Lupinenerzeugnisse.
        /// </summary>
        internal static string A13 {
            get {
                return ResourceManager.GetString("A13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weichtiere und Weichtiererzeugnisse.
        /// </summary>
        internal static string A14 {
            get {
                return ResourceManager.GetString("A14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krebstiere und Krebstiererzeugnisse.
        /// </summary>
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eier und Eiererzeugnisse.
        /// </summary>
        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisch.
        /// </summary>
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erdnüsse und Erdnusserzeugnisse.
        /// </summary>
        internal static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soja und Sojaerzeugnisse.
        /// </summary>
        internal static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milch und Milcherzeugnisse(einschließlich Lactose).
        /// </summary>
        internal static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalenfrüchte sowie daraus hergest. Erzeugnisse.
        /// </summary>
        internal static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellerie und Sellerieerzeugnisse.
        /// </summary>
        internal static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusatzstoffe.
        /// </summary>
        internal static string Additives {
            get {
                return ResourceManager.GetString("Additives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergene.
        /// </summary>
        internal static string Allergens {
            get {
                return ResourceManager.GetString("Allergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcodierungen.
        /// </summary>
        internal static string Bitencodings {
            get {
                return ResourceManager.GetString("Bitencodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy.
        /// </summary>
        internal static string Buddy {
            get {
                return ResourceManager.GetString("Buddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung in Kalender exportieren?.
        /// </summary>
        internal static string CalendarExportQuery {
            get {
                return ResourceManager.GetString("CalendarExportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurse.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string Desserts {
            get {
                return ResourceManager.GetString("Desserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Abrufen der Daten. Bitte später erneut probieren..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Basic Layout.
        /// </summary>
        internal static string ExerciseBasicLayout {
            get {
                return ResourceManager.GetString("ExerciseBasicLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übungen.
        /// </summary>
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gäste.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRZ: 0 = -  |  1 = +
        ///NRZI: 1 = Spannungsveränderung (+/-) 
        ///MLT-3: 1 = abwechselnd +, 0 und -.
        /// </summary>
        internal static string InfoText_BitEncoding {
            get {
                return ResourceManager.GetString("InfoText_BitEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Prozess {0} wird wieder freigegeben..
        /// </summary>
        internal static string InfoText_Buddy_Final {
            get {
                return ResourceManager.GetString("InfoText_Buddy_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Prozess {0} fordert {1} KB an Speicher an. Dem Prozess werden {2} KB zugewiesen..
        /// </summary>
        internal static string InfoText_Buddy_Request {
            get {
                return ResourceManager.GetString("InfoText_Buddy_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die übrig gebliebene Bitfolge wird als Prüfbit bezeichnet und kann im Folgenden für die Prüfung verwendet werden..
        /// </summary>
        internal static string InfoText_CRC_check {
            get {
                return ResourceManager.GetString("InfoText_CRC_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergibt die zum Schluss übrig gebliebene Bitfolge 0, so war die Übertragung erfolgreich..
        /// </summary>
        internal static string InfoText_CRC_check_Finish {
            get {
                return ResourceManager.GetString("InfoText_CRC_check_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die ursprüngliche Bitfolge {0} wird um das Prüfbit {1} erweitert. Anschließend wird eine XOR Division mit dem festen Generatorpolynom 100101 durchgeführt..
        /// </summary>
        internal static string InfoText_CRC_check_Start {
            get {
                return ResourceManager.GetString("InfoText_CRC_check_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf der resultierenden Bitfolge wird wieder eine XOR Division mit dem Generatorpolynom 100101 durchgeführt..
        /// </summary>
        internal static string InfoText_CRC_evenStep {
            get {
                return ResourceManager.GetString("InfoText_CRC_evenStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bitfolge {0} wird um 5 Nullen erweitert. Anschließend wird eine XOR Division mit dem Generatorpolynom 100101 (CRC5) durchgeführt..
        /// </summary>
        internal static string InfoText_CRC_Start {
            get {
                return ResourceManager.GetString("InfoText_CRC_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOR Division wird durchgeführt: 
        ///
        ///1 über 1 ergibt 0 
        ///0 über 0 ergibt 0 
        ///1 über 0 ergibt 1
        ///0 über 1 ergibt 1 
        ///                    
        ///Voranstehende Nullen können weg gelassen werden. Die resultierende Bitfolge wird wieder auf 6 Zeichen erweitert, indem die vorhandenen Bits (Nullen) der Bitfolge heruntergezogen werden..
        /// </summary>
        internal static string InfoText_CRC_unevenStep {
            get {
                return ResourceManager.GetString("InfoText_CRC_unevenStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Element {0} wurde in Kachel {1} eingefügt,.
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Added {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da die Kachel leer stand..
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Added_Empty {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da das Element dieser Kachel nicht mehr genutzt wird..
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Added_NotInUse {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added_NotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Element ist bereits in Kachel {0} vorhanden..
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Exists {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da die letzte Nutzung des Elementes dieser Kachel am weitesten ({0}) in der Vergangenheit lag..
        /// </summary>
        internal static string InfoText_PageReplacement_Fifo_Element_Added_Distance {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Fifo_Element_Added_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da die letzte Nutzung des Elementes dieser Kachel am weitesten {0} in der Vergangenheit lag..
        /// </summary>
        internal static string InfoText_PageReplacement_LRU_Element_Added_Distance {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_LRU_Element_Added_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da die nächste Nutzung des Elementes dieser Kachel am weitesten ({0}) in der Zukunft lag..
        /// </summary>
        internal static string InfoText_PageReplacement_Optimal_Element_Added_NotInUse {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Optimal_Element_Added_NotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zeiger bestimmt, welche Kachel zu erst betrachtet wird: Kachel {0}. 
        ///
        ///Da das Referenzbit dieser Kachel = 1 war, wird dieses zunächst auf 0 gesetzt und anschließend die nächste Kachel betrachtet. 
        ///
        ///Kachel {1} war die erste Kachel mit Referenzbit = 0, in welches das Element eingesetzt werden konnte. 
        ///
        ///Nun zeigt der Zeiger auf: Kachel {1}.
        /// </summary>
        internal static string InfoText_PageReplacement_SecondChanceClock_Element_Added_NotPointer {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_SecondChanceClock_Element_Added_NotPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zeiger bestimmt, welche Kachel zu erst betrachtet wird: Kachel {0}. 
        ///
        ///Da das Referenzbit dieser Kachel = 0 war, konnte das Element eingesetzt werden. 
        ///
        ///Nun zeigt der Zeiger auf Kachel {1}..
        /// </summary>
        internal static string InfoText_PageReplacement_SecondChanceClock_Element_Added_Pointer {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_SecondChanceClock_Element_Added_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Prozess {0} hat gemäß EDF aktuell Priorität, da er die früheste Deadline hat. 
        ///
        ///Er wird gestartet, da kein anderer Prozess mit früherer Deadline rechenbereit ist..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_EDF {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_EDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///EDF = Earliest Deadline First 
        ///
        ///Die Priorität wird von der Deadline des Prozesses abgeleitet. Je früher die Deadline, desto höher die Priorität..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_EDF_Info {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_EDF_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da der Prozess {0} gemäß RMS die höchste Priorität hat, wird er sofort ausgeführt. 
        ///
        ///Der Prozess kann Prozesse mit niedriger und mittlerer Priorität unterbrechen..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_High {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///RMS = Raten Monotones Scheduling 
        ///
        ///Die Priorität wird von der Häufigkeit des Prozesses abgeleitet. Je häufiger ein Prozess vorkommt, desto höher wird er priorisiert..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_Info {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Prozess {0} hat gemäß RMS die niedrigste Priorität. 
        ///
        ///Er wird gestartet, da kein Prozess mit höherer Priorität ansteht. 
        ///
        ///Der Prozess kann von einem Prozess mit mittlerer oder hoher Priorität unterbrochen werden..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_Low {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Prozess {0} hat gemäß RMS mittlere Priorität. 
        ///
        ///Er wird gestartet, da kein Prozess mit höherer Priorität ansteht. \n\nDer Prozess kann einen Prozess mit niedriger Priorität unterbrechen und von einem Prozess mit hoher Priorität unterbrochen werden..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_Medium {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechnung.
        /// </summary>
        internal static string InfoText_Scheduling_Calculation {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        internal static string InfoText_Scheduling_Duration {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Prozesse werden der Reihenfolge nach abgearbeitet. 
        ///            
        ///Für die Gesamtwartezeit wird die Laufzeit eines jeden Prozesses mit der Anzahl an bereiten Prozessen multipliziert, das Ergebnis wird summiert und durch die Anzahl der Prozesse dividiert..
        /// </summary>
        internal static string InfoText_Scheduling_FirstComeFirstServed_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_FirstComeFirstServed_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorität.
        /// </summary>
        internal static string InfoText_Scheduling_Priority {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Prozesse werden der Reihenfolge nach entsprechend ihrer Priorität abgearbeitet. 
        ///
        ///Für die Gesamtwartezeit wird die Laufzeit eines jeden Prozesses mit der jeweiligen Priorität multipliziert, das Ergebnis wird summiert und durch die Anzahl der Prozesse dividiert..
        /// </summary>
        internal static string InfoText_Scheduling_Priority_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Priority_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis.
        /// </summary>
        internal static string InfoText_Scheduling_Result {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach {0} Zeiteinheit:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_AfterTimeUnit {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_AfterTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach {0} Zeiteinheiten:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_AfterTimeUnits {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_AfterTimeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginn:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_Begin {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach dem Round Robin Verfahren wird jedem bereiten Prozess die selbe Rechenzeit gewährt. Wird ein Prozess vollendet, so wird die Rechenzeit erneut aufgeteilt. 
        ///
        ///Die Gesamtwartezeit ergibt sich aus den Zeiteinheiten, welche es braucht, bis ein jeder Prozess vollendet ist, multipliziert mit der jeweiligen Anzahl an bereiten Prozessen, dividiert durch die Gesamtanzahl der Prozesse..
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartezeit:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_WaitingTime {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_WaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Prozesse werden der Reihenfolge nach abgearbeitet, wobei Prozesse mit geringer Laufzeit priorisiert werden.
        ///
        ///Für die Gesamtwartezeit wird die Laufzeit eines jeden Prozesses mit der Anzahl an bereiten Prozessen multipliziert, das Ergebnis wird summiert und durch die Anzahl der Prozesse dividiert..
        /// </summary>
        internal static string InfoText_Scheduling_ShortestJobFirst_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_ShortestJobFirst_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte erlaube Kalenderzugriff in der Einstellungsapp..
        /// </summary>
        internal static string IOSPermissions {
            get {
                return ResourceManager.GetString("IOSPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen.
        /// </summary>
        internal static string Maindishes {
            get {
                return ResourceManager.GetString("Maindishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensa.
        /// </summary>
        internal static string Mensa {
            get {
                return ResourceManager.GetString("Mensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Informationen zu Inhaltsstoffen und Nährwerten gibt es auf der Webseite des Studierendenwerks Paderborn..
        /// </summary>
        internal static string MensaInfo {
            get {
                return ResourceManager.GetString("MensaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimaler Spannbaum.
        /// </summary>
        internal static string MST {
            get {
                return ResourceManager.GetString("MST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der kürzeste Weg um .
        /// </summary>
        internal static string MSTV_Info_1 {
            get {
                return ResourceManager.GetString("MSTV_Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit .
        /// </summary>
        internal static string MSTV_Info_2 {
            get {
                return ResourceManager.GetString("MSTV_Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  zu Verbinden ist über die .
        /// </summary>
        internal static string MSTV_Info_3 {
            get {
                return ResourceManager.GetString("MSTV_Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kante mit der Gewichtung .
        /// </summary>
        internal static string MSTV_Info_4 {
            get {
                return ResourceManager.GetString("MSTV_Info_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzmasken.
        /// </summary>
        internal static string Netmasks {
            get {
                return ResourceManager.GetString("Netmasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerke.
        /// </summary>
        internal static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Werte.
        /// </summary>
        internal static string NewValues {
            get {
                return ResourceManager.GetString("NewValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine editierbaren Kalender..
        /// </summary>
        internal static string NoCalendars {
            get {
                return ResourceManager.GetString("NoCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Essen zur Anzeige. Mensa geschlossen?.
        /// </summary>
        internal static string NoMeals {
            get {
                return ResourceManager.GetString("NoMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betriebssysteme.
        /// </summary>
        internal static string OperatingSystems {
            get {
                return ResourceManager.GetString("OperatingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenersetzung.
        /// </summary>
        internal static string PageReplacement {
            get {
                return ResourceManager.GetString("PageReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalenderzugriff wird für den Export benötigt..
        /// </summary>
        internal static string PermissionRationale {
            get {
                return ResourceManager.GetString("PermissionRationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studierende / Bedienstete / Gäste.
        /// </summary>
        internal static string PricesLabel {
            get {
                return ResourceManager.GetString("PricesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozesse.
        /// </summary>
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profs.
        /// </summary>
        internal static string Profs {
            get {
                return ResourceManager.GetString("Profs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst die Einstellung auch nachher ändern!.
        /// </summary>
        internal static string QueryInfo {
            get {
                return ResourceManager.GetString("QueryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echtzeitscheduling.
        /// </summary>
        internal static string RealtimeScheduling {
            get {
                return ResourceManager.GetString("RealtimeScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folge.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtig.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stundenplan.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchbegriff.
        /// </summary>
        internal static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der kürzeste Weg zu .
        /// </summary>
        internal static string ShortestPath_Info_1 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ausgehend von .
        /// </summary>
        internal static string ShortestPath_Info_2 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ist zu erreichen über: .
        /// </summary>
        internal static string ShortestPath_Info_3 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kürzeste Wege.
        /// </summary>
        internal static string ShortestPaths {
            get {
                return ResourceManager.GetString("ShortestPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösung anzeigen.
        /// </summary>
        internal static string ShowSolution {
            get {
                return ResourceManager.GetString("ShowSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beilagen.
        /// </summary>
        internal static string Sidedishes {
            get {
                return ResourceManager.GetString("Sidedishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppen.
        /// </summary>
        internal static string Soups {
            get {
                return ResourceManager.GetString("Soups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertiefung.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedienstete.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist dein aktueller Status an der HSHL?.
        /// </summary>
        internal static string StatusQuery {
            get {
                return ResourceManager.GetString("StatusQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studierende.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechnung.
        /// </summary>
        internal static string TableLabel_CRC_Calculation {
            get {
                return ResourceManager.GetString("TableLabel_CRC_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfung.
        /// </summary>
        internal static string TableLabel_CRC_Check {
            get {
                return ResourceManager.GetString("TableLabel_CRC_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstand.
        /// </summary>
        internal static string TableLabel_PageReplacement_Distance {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeiger.
        /// </summary>
        internal static string TableLabel_PageReplacement_Pointer {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz.
        /// </summary>
        internal static string TableLabel_PageReplacement_Reference {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kachel.
        /// </summary>
        internal static string TableLabel_PageReplacement_Slot {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsch.
        /// </summary>
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Farbstoff(en).
        /// </summary>
        internal static string Z1 {
            get {
                return ResourceManager.GetString("Z1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enthält eine Phenylalaninquelle.
        /// </summary>
        internal static string Z10 {
            get {
                return ResourceManager.GetString("Z10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Taurin.
        /// </summary>
        internal static string Z11 {
            get {
                return ResourceManager.GetString("Z11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Nitratpökelsalz.
        /// </summary>
        internal static string Z12 {
            get {
                return ResourceManager.GetString("Z12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to koffeinhaltig.
        /// </summary>
        internal static string Z13 {
            get {
                return ResourceManager.GetString("Z13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chininhaltig.
        /// </summary>
        internal static string Z14 {
            get {
                return ResourceManager.GetString("Z14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milcheiweiß.
        /// </summary>
        internal static string Z15 {
            get {
                return ResourceManager.GetString("Z15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Konservierungsstoff(en).
        /// </summary>
        internal static string Z2 {
            get {
                return ResourceManager.GetString("Z2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Antioxidationsmittel.
        /// </summary>
        internal static string Z3 {
            get {
                return ResourceManager.GetString("Z3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Geschmacksverstärker(n).
        /// </summary>
        internal static string Z4 {
            get {
                return ResourceManager.GetString("Z4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Phosphat.
        /// </summary>
        internal static string Z5 {
            get {
                return ResourceManager.GetString("Z5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschwefelt.
        /// </summary>
        internal static string Z6 {
            get {
                return ResourceManager.GetString("Z6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gewachst.
        /// </summary>
        internal static string Z7 {
            get {
                return ResourceManager.GetString("Z7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschwärzt.
        /// </summary>
        internal static string Z8 {
            get {
                return ResourceManager.GetString("Z8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Süßungsmittel(n).
        /// </summary>
        internal static string Z9 {
            get {
                return ResourceManager.GetString("Z9", resourceCulture);
            }
        }
    }
}
